/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsi_ryan;

import java.awt.HeadlessException;
import java.io.File;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.commons.digester.Digester;
/**
 *
 * @author USER
 */
public class FormKalkulator extends javax.swing.JFrame {
private DefaultTableModel model;
    Connection koneksi;
    ResultSet hasil;
    PreparedStatement proses;
    /**
     * Creates new form FormKalkulator
     */
    public FormKalkulator() {
        initComponents();
                     //memberi penamaan pada judul kolom tblGaji;
             model = new DefaultTableModel ( );
             tblPengeluaran.setModel(model);
             model.addColumn("Belanjaan");
             model.addColumn("Belanjaan");
             model.addColumn("Belanjaan");
             model.addColumn("Belanjaan");
             model.addColumn("Belanjaan"); 
             model.addColumn("Belanjaan");
             model.addColumn("Belanjaan");
             model.addColumn("Tanggal");
             model.addColumn("Pengeluaran"); 
             
             getData(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jMenu1 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        txtGaram = new javax.swing.JTextField();
        txtRagi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtGula = new javax.swing.JTextField();
        txtAir = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnSubmitPrint = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtjumlah = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTepung = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTelur = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMargarin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableBelanja = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtBelanjaan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtBelanjaan5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtBelanjaan2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtBelanjaan6 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtBelanjaan4 = new javax.swing.JTextField();
        txtBelanjaan7 = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtBelanjaan3 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPengeluaran = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        txtTanggal = new com.toedter.calendar.JDateChooser();
        BtnResetluaran = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblLaporan = new javax.swing.JTable();
        DateDari = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        DateKe = new com.toedter.calendar.JDateChooser();
        btnPengeluaran = new javax.swing.JButton();
        BtnTerjual = new javax.swing.JButton();
        BtnSuplier = new javax.swing.JButton();
        Txttotal = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        btnProduksi = new javax.swing.JButton();
        btnCacad = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        Logout = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Resep Kalkulator Roti Manis");

        jLabel6.setText("Ragi");

        txtGaram.setEditable(false);
        txtGaram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGaramActionPerformed(evt);
            }
        });

        txtRagi.setEditable(false);

        jLabel7.setText("gula ");

        txtGula.setEditable(false);

        txtAir.setEditable(false);
        txtAir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirActionPerformed(evt);
            }
        });

        jLabel8.setText("Air ");

        btnSubmitPrint.setText("Submit");
        btnSubmitPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitPrintActionPerformed(evt);
            }
        });

        BtnReset.setText("Reset");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        jLabel1.setText("Roti :");

        txtjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahActionPerformed(evt);
            }
        });
        txtjumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjumlahKeyReleased(evt);
            }
        });

        jLabel2.setText("Pcs");

        txtTepung.setEditable(false);

        jLabel3.setText("Tepung");

        jLabel4.setText("Telur");

        txtTelur.setEditable(false);
        txtTelur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelurActionPerformed(evt);
            }
        });

        jLabel5.setText("Margarin");

        txtMargarin.setEditable(false);

        jLabel9.setText("Garam");

        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtGaram, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtRagi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtGula, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtAir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnSubmitPrint, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(BtnReset, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtjumlah, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtTepung, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtTelur, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtMargarin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtMargarin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(txtTepung)
                    .addComponent(txtjumlah)
                    .addComponent(txtTelur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(26, 26, 26)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(txtAir, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnReset))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(txtGula, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSubmitPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(28, 28, 28)
                            .addComponent(txtRagi))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(txtGaram, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTepung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTelur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMargarin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtGaram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtRagi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtGula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(btnSubmitPrint)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnReset)
                                .addGap(3, 3, 3)))))
                .addGap(36, 36, 36))
        );

        TableBelanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TableBelanja);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 48, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(294, 294, 294)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("RESEP KALKULATOR", jPanel1);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Pengeluaran");

        jLabel12.setText("Nama Belanjaan1  :");

        txtBelanjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBelanjaanActionPerformed(evt);
            }
        });

        jLabel13.setText("Nama Belanjaan5  :");

        jLabel14.setText("Nama Belanjaan2  :");

        jLabel15.setText("Nama Belanjaan6  :");

        jLabel16.setText("Nama Belanjaan3  :");

        jLabel17.setText("Perhatian !! ");

        jLabel18.setText("Tanggal              :");

        jLabel19.setText("Nama Belanjaan4  :");

        jLabel20.setText("Nama Belanjaan7 :");

        jLabel21.setText("Total Harga        :");

        tblPengeluaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblPengeluaran);

        jLabel22.setText("Jika barangnya lebih dari 7 field harap inputkan di selanjutnya!!");

        jLabel23.setText("Jika Field nya ada yang kosong harap isi saja Kosong !!");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        txtTanggal.setDateFormatString("yyyy-MM-dd");

        BtnResetluaran.setText("Reset");
        BtnResetluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetluaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBelanjaan2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBelanjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBelanjaan6)
                            .addComponent(txtBelanjaan5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBelanjaan3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBelanjaan4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BtnResetluaran)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSubmit))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtBelanjaan7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel21))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTotal)
                                            .addComponent(txtTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(131, 131, 131))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel17)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtBelanjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtBelanjaan5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtBelanjaan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtBelanjaan6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBelanjaan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtBelanjaan4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBelanjaan7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(btnSubmit)
                            .addComponent(BtnResetluaran))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23))
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("PENGELUARAN", jPanel2);

        tblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblLaporan);

        DateDari.setDateFormatString("yyyy-MM-dd");

        jLabel24.setText("Dari    :");

        jLabel25.setText("Ke    :");

        DateKe.setDateFormatString("yyyy-MM-dd");

        btnPengeluaran.setText("Pengeluaran");
        btnPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengeluaranActionPerformed(evt);
            }
        });

        BtnTerjual.setText("Terjual");
        BtnTerjual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTerjualActionPerformed(evt);
            }
        });

        BtnSuplier.setText("Suplier");
        BtnSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSuplierActionPerformed(evt);
            }
        });

        jLabel26.setText("Total     :");

        btnProduksi.setText("Produksi");
        btnProduksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduksiActionPerformed(evt);
            }
        });

        btnCacad.setText("Cacad");
        btnCacad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCacadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnPengeluaran)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnTerjual)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnSuplier)
                                .addGap(18, 18, 18)
                                .addComponent(btnProduksi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCacad))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(DateDari, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(DateKe, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(DateDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(DateKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPengeluaran)
                    .addComponent(BtnTerjual)
                    .addComponent(BtnSuplier)
                    .addComponent(btnProduksi)
                    .addComponent(btnCacad))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LAPORAN", jPanel3);

        jMenu2.setText("Logout");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jMenu2.add(Logout);

        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelurActionPerformed

    private void txtjumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlahKeyReleased
        // TODO add your handling code here:
        int t, j , k;
        t = Integer.parseInt(txtjumlah.getText());
        j = 500;
        k = j*t;
        txtTepung.setText(""+k+"Gram");

        int rt,jml,telur;
        rt = Integer.parseInt(txtjumlah.getText());
        jml = 1;
        telur = rt * jml;
        txtTelur.setText(""+telur+"Telur");

        int mg,ml ;
        mg = 75;
        ml = mg * rt;
        txtMargarin.setText(""+ml+"Gram");

        int rg,gm;
        rg = 11;
        gm = rg * rt;
        txtRagi.setText(""+gm+"Gram");

        int gp,jmlh;
        gp = 100;
        jmlh = rt * gp;
        txtGula.setText(""+jmlh+"Gram");

        int air,roti;
        air = 300;
        roti = rt * air;
        txtAir.setText(""+roti+"ml");

        int garam,jmlah;
        garam = (int) 2.5;
        jmlah = garam * rt;
        txtGaram.setText(""+jmlah+"Gram");
    }//GEN-LAST:event_txtjumlahKeyReleased

    private void txtjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahActionPerformed

    private void btnSubmitPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitPrintActionPerformed
        // TODO add your handling code here:
        Connection koneksi = null;
        Statement stmt = null;
        try {

            koneksi = KoneksiDB.ConnectDb();
            stmt = koneksi.createStatement();
            stmt.executeUpdate("INSERT INTO `resep`( `resep_1`, `resep_2`, `resep_3`, `resep_4`, `resep_5`, `resep_6`, `resep_7`) VALUES ('"+txtTepung.getText()+"','"+txtTelur.getText()+"','"+txtMargarin.getText()+"','"+txtRagi.getText()+"','"+txtGula.getText()+"','"+txtAir.getText()+"','"+txtGaram.getText()+"')");
            int y = Integer.parseInt(txtjumlah.getText());
            for (int i = 0; i < y; i++) {
                LocalDate pembuatan = LocalDate.now();
                LocalDate kadaluarsa = LocalDate.now().plusMonths(3);
                stmt.executeUpdate("INSERT INTO `produksi` (`nama_roti`, `tgl_pembuatan`, `tgl_kadaluarsa`, `harga`) VALUES ('Roti Manis', '"+pembuatan+"', '"+kadaluarsa+"', '10000')");
            }
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI TAMBAHKAN KE DATABASE!");
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, "DATA GAGAL DITAMBAHKAN");
        }
    }//GEN-LAST:event_btnSubmitPrintActionPerformed

    private void txtGaramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGaramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGaramActionPerformed

    private void txtAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        Connection koneksi = null;
        Statement stmt = null;
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String Tanggal = dateFormat.format(txtTanggal.getDate());
            koneksi = KoneksiDB.ConnectDb();
            stmt = koneksi.createStatement();
            stmt.executeUpdate("INSERT INTO `belanja`(`belanja_1`, `belanja_2`, `belanja_3`, `belanja_4`, `belanja_5`, `belanja_6`, `belanja_7`, `Tanggal`, `total_pengeluaran`) VALUES ('"+txtBelanjaan.getText()+"','"+txtBelanjaan2.getText()+"','"+txtBelanjaan3.getText()+"','"+txtBelanjaan4.getText()+"','"+txtBelanjaan5.getText()+"','"+txtBelanjaan6.getText()+"','"+txtBelanjaan7.getText()+"','"+Tanggal+"','"+txtTotal.getText()+"')");
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI TAMBAHKAN KE DATABASE!");
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, "DATA GAGAL DITAMBAHKAN");
        }
        getData();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtBelanjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBelanjaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBelanjaanActionPerformed

    private void BtnResetluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetluaranActionPerformed
        // TODO add your handling code here:
        txtBelanjaan.setText("");
        txtBelanjaan2.setText("");
        txtBelanjaan3.setText("");
        txtBelanjaan4.setText("");
        txtBelanjaan5.setText("");
        txtBelanjaan6.setText("");
        txtBelanjaan7.setText("");
        txtTotal.setText("");
        java.util.Date start = new java.util.Date();
        txtTanggal.setDate(start);
    }//GEN-LAST:event_BtnResetluaranActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        // TODO add your handling code here:
        txtjumlah.setText("");
        txtTepung.setText("");
        txtTelur.setText("");
        txtMargarin.setText("");
        txtGaram.setText("");
        txtRagi.setText("");
        txtGula.setText("");
        txtAir.setText("");
    }//GEN-LAST:event_BtnResetActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(
        null,"Yakin Ingin Logout?","Konfirmasi Keluar Aplikasi",JOptionPane.YES_NO_OPTION);
        if(reply == JOptionPane.YES_NO_OPTION)
        {
            java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FormLogin().setVisible(true);
                dispose();
            }
        });
        }
    }//GEN-LAST:event_LogoutActionPerformed
    private void pengeluaran_table(){
        DefaultTableModel model = new DefaultTableModel();
            model.addColumn("No.B");
            model.addColumn("Belanjaan");
            model.addColumn("Belanjaan");
            model.addColumn("Belanjaan");
            model.addColumn("Belanjaan");
            model.addColumn("Belanjaan");
            model.addColumn("Belanjaan");
            model.addColumn("Belanjaan");
            model.addColumn("Tanggal");
            model.addColumn("Pengeluaran");
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String Dari = dateFormat.format(DateDari.getDate());
    String Ke = dateFormat.format(DateKe.getDate());
    int var =1;
    try{
            String sql = "SELECT `id_belanja`, `belanja_1`, `belanja_2`, `belanja_3`, `belanja_4`, `belanja_5`, `belanja_6`, `belanja_7`, `Tanggal`, `total_pengeluaran` FROM `belanja` WHERE belanja.Tanggal BETWEEN '"+Dari+"' AND '"+Ke+"'";
            Connection koneksi = KoneksiDB.ConnectDb();
            PreparedStatement proses = koneksi.prepareStatement(sql);
            ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                model.addRow(new Object[]{hasil.getString(1),hasil.getString(2),hasil.getString(3),hasil.getString(4),hasil.getString(5),hasil.getString(6),hasil.getString(7),hasil.getString(8),hasil.getString(9),hasil.getString(10)});
                
                }
            tblLaporan.setModel(model);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
        }
    }
    private void totalpengeluaran(){
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String Dari = dateFormat.format(DateDari.getDate());
    String Ke = dateFormat.format(DateKe.getDate());  
    
     try{
            String sql = "SELECT SUM(total_pengeluaran) FROM belanja WHERE belanja.id_belanja AND belanja.Tanggal BETWEEN '"+Dari+"' AND '"+Ke+"'";
        Connection koneksi = KoneksiDB.ConnectDb();
        PreparedStatement proses = koneksi.prepareStatement(sql);
        ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                Txttotal.setText(hasil.getString(1));
                
                }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
        }
     
    }
    private void jasper_pengeluaran(){
        koneksi = skripsi_ryan.KoneksiDB.ConnectDb();
            try {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String Dari = dateFormat.format(DateDari.getDate());
            String Ke = dateFormat.format(DateKe.getDate());  
                HashMap param = new HashMap();
                    param.put("Dari",Dari);
                    param.put("Ke",Ke);
                    
                JasperPrint jp = JasperFillManager.fillReport("src/Print/pengeluaran.jasper", param , koneksi);
                    JRViewer jasperViewer = new JRViewer(jp);
                    JasperViewer jv=new JasperViewer(jp,false);
                    jv.setVisible(true);
            } catch(JRException e) {
                JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
            }
    }
    private void btnPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengeluaranActionPerformed
        // TODO add your handling code here:
        pengeluaran_table();
        totalpengeluaran();
        jasper_pengeluaran();
    }//GEN-LAST:event_btnPengeluaranActionPerformed
    private void searchproduksi(){
    
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Roti");
    model.addColumn("Nama Roti");
    model.addColumn("Tanggal Pembuatan");
    model.addColumn("Tanggal Kadaluarsa");
    model.addColumn("Harga");
    model.addColumn("Status");
    
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String Dari = dateFormat.format(DateDari.getDate());
    String Ke = dateFormat.format(DateKe.getDate());
    Txttotal.setText("");
    int var =1;
    try{
            String sql = "SELECT `kode_roti`, `nama_roti`, `tgl_pembuatan`, `tgl_kadaluarsa`, `harga`, `status` FROM `produksi` WHERE `status`='Produksi' AND tgl_pembuatan BETWEEN '"+Dari+"' AND '"+Ke+"' ORDER BY tgl_pembuatan ASC";
        Connection koneksi = KoneksiDB.ConnectDb();
        PreparedStatement proses = koneksi.prepareStatement(sql);
        ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                model.addRow(new Object[]{hasil.getString(1),hasil.getString(2),hasil.getString(3),hasil.getString(4),hasil.getString(5),hasil.getString(6)});
                
                }
            tblLaporan.setModel(model);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
        }
    }
    private void countproduksi(){
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String Dari = dateFormat.format(DateDari.getDate());
    String Ke = dateFormat.format(DateKe.getDate());  
    
     try{
            String sql = "SELECT COUNT(status) FROM produksi WHERE status='produksi' AND tgl_pembuatan BETWEEN '"+Dari+"' AND '"+Ke+"'";
        Connection koneksi = KoneksiDB.ConnectDb();
        PreparedStatement proses = koneksi.prepareStatement(sql);
        ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                Txttotal.setText(hasil.getString(1));
                
                }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
        }
     
    }
    private void btnProduksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduksiActionPerformed
        // TODO add your handling code here:
        searchproduksi();
        countproduksi();
    }//GEN-LAST:event_btnProduksiActionPerformed
    
    
    private void Searchterjual(){
    
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Roti");
    model.addColumn("Nama Roti");
    model.addColumn("Tanggal Pembuatan");
    model.addColumn("Tanggal Kadaluarsa");
    model.addColumn("Harga");
    model.addColumn("Status");
    
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String Dari = dateFormat.format(DateDari.getDate());
    String Ke = dateFormat.format(DateKe.getDate());
    int var =1;
    try{
            String sql = "SELECT `kode_roti`, `nama_roti`, `tgl_pembuatan`, `tgl_kadaluarsa`, `harga`, `status` FROM `produksi` WHERE `status`='Terjual' AND tgl_pembuatan BETWEEN '"+Dari+"' AND '"+Ke+"' ORDER BY tgl_pembuatan ASC";
            Connection koneksi = KoneksiDB.ConnectDb();
        PreparedStatement proses = koneksi.prepareStatement(sql);
        ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                model.addRow(new Object[]{hasil.getString(1),hasil.getString(2),hasil.getString(3),hasil.getString(4),hasil.getString(5),hasil.getString(6)});
                
                }
            tblLaporan.setModel(model);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
        }
    }
    private void totalterjual(){
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String Dari = dateFormat.format(DateDari.getDate());
    String Ke = dateFormat.format(DateKe.getDate());  
    
     try{
            String sql = "SELECT SUM(harga) FROM produksi WHERE status='Terjual' AND tgl_pembuatan BETWEEN '"+Dari+"' AND '"+Ke+"'";
            Connection koneksi = KoneksiDB.ConnectDb();
        PreparedStatement proses = koneksi.prepareStatement(sql);
        ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                Txttotal.setText(hasil.getString(1));
                
                }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
        }
    }
    private void jasper_terjual(){
        koneksi = skripsi_ryan.KoneksiDB.ConnectDb();
            try {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String Dari = dateFormat.format(DateDari.getDate());
            String Ke = dateFormat.format(DateKe.getDate());  
                HashMap param = new HashMap();
                    param.put("Dari",Dari);
                    param.put("Ke",Ke);
                    
                JasperPrint jp = JasperFillManager.fillReport("src/Print/Terjual.jasper", param , koneksi);
                    JRViewer jasperViewer = new JRViewer(jp);
                    JasperViewer jv=new JasperViewer(jp,false);
                    jv.setVisible(true);
            } catch(JRException e) {
                JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
            }
    }
    private void BtnTerjualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTerjualActionPerformed
        // TODO add your handling code here:
        Searchterjual();
        totalterjual();
        jasper_terjual();
    }//GEN-LAST:event_BtnTerjualActionPerformed
    private void Searchsupplier(){
    
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Roti");
    model.addColumn("Nama Roti");
    model.addColumn("Tanggal Pembuatan");
    model.addColumn("Tanggal Kadaluarsa");
    model.addColumn("Harga");
    model.addColumn("Status");
    
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String Dari = dateFormat.format(DateDari.getDate());
    String Ke = dateFormat.format(DateKe.getDate());
    int var =1;
    try{
            String sql = "SELECT `kode_roti`, `nama_roti`, `tgl_pembuatan`, `tgl_kadaluarsa`, `harga`, `status` FROM `produksi` WHERE `status`='Supplier' AND tgl_pembuatan BETWEEN '"+Dari+"' AND '"+Ke+"' ORDER BY tgl_pembuatan ASC";
            Connection koneksi = KoneksiDB.ConnectDb();
        PreparedStatement proses = koneksi.prepareStatement(sql);
        ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                model.addRow(new Object[]{hasil.getString(1),hasil.getString(2),hasil.getString(3),hasil.getString(4),hasil.getString(5),hasil.getString(6)});
                
                }
            tblLaporan.setModel(model);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
        }
    }    
    private void totalsuplier(){
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String Dari = dateFormat.format(DateDari.getDate());
    String Ke = dateFormat.format(DateKe.getDate());  
    
     try{
            String sql = "SELECT SUM(harga) FROM produksi WHERE status='Supplier' AND tgl_pembuatan BETWEEN '"+Dari+"' AND '"+Ke+"'";
            Connection koneksi = KoneksiDB.ConnectDb();
        PreparedStatement proses = koneksi.prepareStatement(sql);
        ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                Txttotal.setText(hasil.getString(1));
                
                }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
        }
    }
    private void jasper_suplier(){
        koneksi = skripsi_ryan.KoneksiDB.ConnectDb();
            try {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String Dari = dateFormat.format(DateDari.getDate());
            String Ke = dateFormat.format(DateKe.getDate());  
                HashMap param = new HashMap();
                    param.put("Dari",Dari);
                    param.put("Ke",Ke);
                    
                JasperPrint jp = JasperFillManager.fillReport("src/Print/Suplier.jasper", param , koneksi);
                    JRViewer jasperViewer = new JRViewer(jp);
                    JasperViewer jv=new JasperViewer(jp,false);
                    jv.setVisible(true);
            } catch(JRException e) {
                JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
            }
    }
    private void BtnSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSuplierActionPerformed
        // TODO add your handling code here:
        Searchsupplier();
        totalsuplier();
        jasper_suplier();
    }//GEN-LAST:event_BtnSuplierActionPerformed
        
    private void Searchcacad(){
    
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Roti");
    model.addColumn("Nama Roti");
    model.addColumn("Tanggal Pembuatan");
    model.addColumn("Tanggal Kadaluarsa");
    model.addColumn("Harga");
    model.addColumn("Status");
    
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String Dari = dateFormat.format(DateDari.getDate());
    String Ke = dateFormat.format(DateKe.getDate());
    int var =1;
    try{
            String sql = "SELECT `kode_roti`, `nama_roti`, `tgl_pembuatan`, `tgl_kadaluarsa`, `harga`, `status` FROM `produksi` WHERE `status`='Cacad' AND tgl_pembuatan BETWEEN '"+Dari+"' AND '"+Ke+"' ORDER BY tgl_pembuatan ASC";
            Connection koneksi = KoneksiDB.ConnectDb();
        PreparedStatement proses = koneksi.prepareStatement(sql);
        ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                model.addRow(new Object[]{hasil.getString(1),hasil.getString(2),hasil.getString(3),hasil.getString(4),hasil.getString(5),hasil.getString(6)});
                
                }
            tblLaporan.setModel(model);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
        }
    }
    private void totalcacad(){
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String Dari = dateFormat.format(DateDari.getDate());
    String Ke = dateFormat.format(DateKe.getDate());  
    
     try{
            String sql = "SELECT SUM(harga) FROM produksi WHERE status='Cacad' AND tgl_pembuatan BETWEEN '"+Dari+"' AND '"+Ke+"'";
            Connection koneksi = KoneksiDB.ConnectDb();
        PreparedStatement proses = koneksi.prepareStatement(sql);
        ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                Txttotal.setText(hasil.getString(1));
                
                }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
        }
    }
    private void jasper_cacad(){
        koneksi = skripsi_ryan.KoneksiDB.ConnectDb();
            try {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String Dari = dateFormat.format(DateDari.getDate());
            String Ke = dateFormat.format(DateKe.getDate());  
                HashMap param = new HashMap();
                    param.put("Dari",Dari);
                    param.put("Ke",Ke);
                    
                JasperPrint jp = JasperFillManager.fillReport("src/Print/Cacad.jasper", param , koneksi);
                    JRViewer jasperViewer = new JRViewer(jp);
                    JasperViewer jv=new JasperViewer(jp,false);
                    jv.setVisible(true);
            } catch(JRException e) {
                JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
            }
    }
    private void btnCacadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCacadActionPerformed
        // TODO add your handling code here:
        Searchcacad();
        totalcacad();
        jasper_cacad();
    }//GEN-LAST:event_btnCacadActionPerformed
    public void getData( ){
     //menghapus isi table tblGaji
     model.getDataVector( ).removeAllElements( );
     model.fireTableDataChanged( );

     try{
           //membuat statemen pemanggilan data pada table tblGaji dari database
           Statement stat = (Statement) KoneksiDB.ConnectDb().createStatement( );
           String sql        = "Select * from belanja";
           ResultSet res   = stat.executeQuery(sql);

           //penelusuran baris pada tabel tblGaji dari database
           while(res.next ()){
                Object[ ] obj = new Object[9];
                obj[0] = res.getString("belanja_1"); 
                obj[1] = res.getString("belanja_2");
                obj[2] = res.getString("belanja_3"); 
                obj[3] = res.getString("belanja_4");
                obj[4] = res.getString("belanja_5"); 
                obj[5] = res.getString("belanja_6");
                obj[6] = res.getString("belanja_7");
                obj[7] = res.getString("Tanggal");
                obj[8] = res.getString("total_pengeluaran");
                model.addRow(obj);
            }
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnResetluaran;
    private javax.swing.JButton BtnSuplier;
    private javax.swing.JButton BtnTerjual;
    private com.toedter.calendar.JDateChooser DateDari;
    private com.toedter.calendar.JDateChooser DateKe;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JTable TableBelanja;
    private javax.swing.JTextField Txttotal;
    private javax.swing.JToggleButton btnCacad;
    private javax.swing.JButton btnPengeluaran;
    private javax.swing.JButton btnProduksi;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSubmitPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblLaporan;
    private javax.swing.JTable tblPengeluaran;
    private javax.swing.JTextField txtAir;
    private javax.swing.JTextField txtBelanjaan;
    private javax.swing.JTextField txtBelanjaan2;
    private javax.swing.JTextField txtBelanjaan3;
    private javax.swing.JTextField txtBelanjaan4;
    private javax.swing.JTextField txtBelanjaan5;
    private javax.swing.JTextField txtBelanjaan6;
    private javax.swing.JTextField txtBelanjaan7;
    private javax.swing.JTextField txtGaram;
    private javax.swing.JTextField txtGula;
    private javax.swing.JTextField txtMargarin;
    private javax.swing.JTextField txtRagi;
    private com.toedter.calendar.JDateChooser txtTanggal;
    private javax.swing.JTextField txtTelur;
    private javax.swing.JTextField txtTepung;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtjumlah;
    // End of variables declaration//GEN-END:variables

    private TableModel resultSetToTableModel(ResultSet sql) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
