/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsi_ryan;

import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class FormAdmin extends javax.swing.JFrame {
private DefaultTableModel model;
    /**
     * Creates new form FormAdmin
     */
    public FormAdmin() {
        initComponents();
        auto_number();
         model = new DefaultTableModel ( );
             tblSup.setModel(model);
             model.addColumn("Kode Suplier");
             model.addColumn("Nama Suplier");
             model.addColumn("Alamat");
             model.addColumn("Telepon");
             model.addColumn("Status"); 
             
             getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboxStatus = new javax.swing.JComboBox<>();
        txtNamaRoti = new javax.swing.JTextField();
        TxtKodeRoti = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableroti = new javax.swing.JTable();
        TxtSell = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableSiapJual = new javax.swing.JTable();
        btnCetakJual = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        BtnReset = new javax.swing.JButton();
        txtUang = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtkodsup = new javax.swing.JTextField();
        txtnamasup = new javax.swing.JTextField();
        txtTeleponsup = new javax.swing.JTextField();
        btnBuat = new javax.swing.JButton();
        comboxsup = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        Alamatsup = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblSup = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        btnResetSup = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtkodeSup = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtQuantitysup = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtKodeRoti = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnSubmitSup = new javax.swing.JButton();
        BtnJualSup = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblSellSup = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblSup1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        comboxsupstatus = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        TxtHarga1 = new javax.swing.JTextField();
        txtTotalsup = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        NamaRotiSup = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        ResetSup = new javax.swing.JButton();
        txtUangsup = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtKembaliansup = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        Logout = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kode Roti :");

        jLabel2.setText("Nama Roti :");

        jLabel3.setText("Status       :");

        comboxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Terjual" }));
        comboxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxStatusActionPerformed(evt);
            }
        });

        txtNamaRoti.setEditable(false);

        TxtKodeRoti.setEditable(false);

        jLabel4.setText("Quantity   :");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        tableroti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Roti", "Nama Roti", "Status", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tableroti);

        TxtSell.setText("Search RTS");
        TxtSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSellActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Perhatian !! ");

        jLabel6.setText("Pertama click siap di jual lalu ,click data nya pada table ,Lalu Print dan jual");

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        TableSiapJual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableSiapJual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSiapJualMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableSiapJual);

        btnCetakJual.setText("Cetak Dan Jual");
        btnCetakJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakJualActionPerformed(evt);
            }
        });
        btnCetakJual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCetakJualKeyPressed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Table Sipa Di Jual");

        jLabel22.setBackground(new java.awt.Color(51, 0, 51));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Table Roti");

        txtHarga.setEditable(false);

        jLabel20.setText("Total          :");

        jLabel23.setText("Harga       :");

        BtnReset.setText("Reset");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        txtUang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUangKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUangKeyReleased(evt);
            }
        });

        jLabel25.setText("Uang         :");

        jLabel28.setText("Kembalian   :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 279, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNamaRoti, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtKodeRoti, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel23)
                                                        .addComponent(jLabel20))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(4, 4, 4))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel28)))
                                        .addGap(28, 28, 28)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(txtTotal)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtSell, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCetakJual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtKodeRoti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(TxtSell)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(comboxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNamaRoti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnReset)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnSubmit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnCetakJual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Penjualan", jPanel1);

        jLabel7.setText("Nama Suplier                    : ");

        jLabel8.setText("Kode Suplier                     :");

        jLabel9.setText("Alamat Suplier                  :");

        jLabel10.setText("No. Telepon/Handpone    :");

        btnBuat.setText("Buat");
        btnBuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuatActionPerformed(evt);
            }
        });

        comboxsup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak Aktif" }));

        Alamatsup.setColumns(20);
        Alamatsup.setRows(5);
        jScrollPane3.setViewportView(Alamatsup);

        jLabel12.setText("Status  :");

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        tblSup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblSup);

        jScrollPane4.setViewportView(jScrollPane5);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Table Supplier");

        btnResetSup.setText("Reset");
        btnResetSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetSupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtkodsup))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnamasup))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(txtTeleponsup))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnBuat)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnResetSup)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(comboxsup, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtkodsup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboxsup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtnamasup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTeleponsup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuat)
                            .addComponent(btnEdit)
                            .addComponent(btnResetSup))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Buat Suplier", jPanel2);

        jLabel13.setText("Kode Suplier : ");

        jLabel14.setText("Quantity      : ");

        jLabel15.setText("Kode Roti     :");

        txtKodeRoti.setEditable(false);

        jButton1.setText("Search RTS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSubmitSup.setText("Submit");
        btnSubmitSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitSupActionPerformed(evt);
            }
        });

        BtnJualSup.setText("Cetak Dan Jual");
        BtnJualSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJualSupActionPerformed(evt);
            }
        });
        BtnJualSup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnJualSupKeyPressed(evt);
            }
        });

        tblSellSup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Supplier", "Kode Roti", "Harga", "Nama Roti"
            }
        ));
        jScrollPane6.setViewportView(tblSellSup);

        tblSup1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSup1MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblSup1);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Table Roti Atau Supplier");

        comboxsupstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Supplier", "Terjual" }));

        jLabel17.setText("Status       :");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Table Roti ");

        jLabel24.setText("Harga           :");

        TxtHarga1.setEditable(false);

        txtTotalsup.setEditable(false);

        jButton2.setText("Suplier Pembayaran");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel26.setText("Nama Roti   :");

        NamaRotiSup.setEditable(false);

        jLabel27.setText("Total           :");

        ResetSup.setText("Reset");
        ResetSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetSupActionPerformed(evt);
            }
        });

        txtUangsup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUangsupKeyReleased(evt);
            }
        });

        jLabel29.setText("Uang          :");

        jLabel30.setText("Kembalian  :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtKodeRoti))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtkodeSup))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQuantitysup))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel29)
                                        .addComponent(jLabel27)
                                        .addComponent(jLabel30))
                                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTotalsup)
                                .addComponent(comboxsupstatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUangsup)
                                .addComponent(NamaRotiSup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtKembaliansup, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 107, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnJualSup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7)
                            .addComponent(jScrollPane6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btnSubmitSup, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jButton2)
                        .addGap(56, 56, 56)
                        .addComponent(ResetSup, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtkodeSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(NamaRotiSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtKodeRoti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUangsup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29)))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtQuantitysup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalsup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(comboxsupstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(BtnJualSup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtKembaliansup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResetSup)
                    .addComponent(btnSubmitSup)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jTabbedPane2.addTab("Supplier", jPanel3);

        Logout.setText("Logout");

        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Logout.add(jMenuItem1);

        jMenuBar1.add(Logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(
        null,"Yakin Ingin Logout?","Konfirmasi Keluar Aplikasi",JOptionPane.YES_NO_OPTION);
        if(reply == JOptionPane.YES_NO_OPTION)
        {
            java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FormLogin().setVisible(true);
                dispose();
            }
        });
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    public void getData( ){
     //menghapus isi table tblGaji
     model.getDataVector( ).removeAllElements( );
     model.fireTableDataChanged( );

     try{
           //membuat statemen pemanggilan data pada table tblGaji dari database
           Statement stat = (Statement) KoneksiDB.ConnectDb().createStatement( );
           String sql        = "Select * from suplier";
           ResultSet res   = stat.executeQuery(sql);

           //penelusuran baris pada tabel tblGaji dari database
           while(res.next ()){
                Object[ ] obj = new Object[5];
                obj[0] = res.getString("kode_supleir"); 
                obj[1] = res.getString("nama_suplier");
                obj[2] = res.getString("alamat"); 
                obj[3] = res.getString("telepon");
                obj[4] = res.getString("status"); 
                model.addRow(obj);
            }
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
}
    private void searchsiapjual(){
    
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Roti");
    model.addColumn("Nama Roti");
    model.addColumn("Tanggal Pembuatan");
    model.addColumn("Tanggal Kadaluarsa");
    model.addColumn("Harga");
    model.addColumn("Status");
    
    int var =1;
    try{
            String sql = "SELECT `kode_roti`, `nama_roti`, `tgl_pembuatan`, `tgl_kadaluarsa`, `harga`, `status` FROM `produksi` WHERE `status` = 'ReadyToSell'";
        Connection koneksi = KoneksiDB.ConnectDb();
        PreparedStatement proses = koneksi.prepareStatement(sql);
        ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                model.addRow(new Object[]{hasil.getString(1),hasil.getString(2),hasil.getString(3),hasil.getString(4),hasil.getString(5),hasil.getString(6)});
                
                }
            TableSiapJual.setModel(model);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
        }
    }
    private void searchsiapjualsuplier(){
    
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Roti");
    model.addColumn("Nama Roti");
    model.addColumn("Tanggal Pembuatan");
    model.addColumn("Tanggal Kadaluarsa");
    model.addColumn("Harga");
    model.addColumn("Status");
    
    int var =1;
    try{
            String sql = "SELECT `kode_roti`, `nama_roti`, `tgl_pembuatan`, `tgl_kadaluarsa`, `harga`, `status` FROM `produksi` WHERE `status` = 'ReadyToSell'";
        Connection koneksi = KoneksiDB.ConnectDb();
        PreparedStatement proses = koneksi.prepareStatement(sql);
        ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                model.addRow(new Object[]{hasil.getString(1),hasil.getString(2),hasil.getString(3),hasil.getString(4),hasil.getString(5),hasil.getString(6)});
                
                }
            tblSup1.setModel(model);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
        }
    }
private void searchsuplier(){
    
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Roti");
    model.addColumn("Nama Roti");
    model.addColumn("Tanggal Pembuatan");
    model.addColumn("Tanggal Kadaluarsa");
    model.addColumn("Harga");
    model.addColumn("Status");
    model.addColumn("Kode Sup");
    
    int var =1;
    try{
            String sql = "SELECT `kode_roti`, `nama_roti`, `tgl_pembuatan`, `tgl_kadaluarsa`, `harga`, `status` , `suplier_kode` FROM `produksi` WHERE `status` = 'Supplier'";
        Connection koneksi = KoneksiDB.ConnectDb();
        PreparedStatement proses = koneksi.prepareStatement(sql);
        ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                model.addRow(new Object[]{hasil.getString(1),hasil.getString(2),hasil.getString(3),hasil.getString(4),hasil.getString(5),hasil.getString(6),hasil.getString(7)});
                
                }
            tblSup1.setModel(model);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
        }
    }
        
    private void TxtSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSellActionPerformed
        // TODO add your handling code here:
        searchsiapjual();
    }//GEN-LAST:event_TxtSellActionPerformed

    private void TableSiapJualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSiapJualMouseClicked
        // TODO add your handling code here:
        int selectedRow = TableSiapJual.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)TableSiapJual.getModel();
        TxtKodeRoti.setText(model.getValueAt(selectedRow, 0).toString());
        txtNamaRoti.setText(model.getValueAt(selectedRow, 1).toString());
        txtHarga.setText(model.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_TableSiapJualMouseClicked

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:  
        DefaultTableModel model = (DefaultTableModel)tableroti.getModel();
        String Status = (String) this.comboxStatus.getSelectedItem();
        String Kode = this.TxtKodeRoti.getText();
        String NamaRoti = this.txtNamaRoti.getText(); 
        String harga = this.txtHarga.getText();
        model.addRow(new Object[]{Kode,NamaRoti,Status,harga});
        for(int i = 0; i < tableroti.getRowCount();i++){
            int y = tableroti.getRowCount();
            txtQuantity.setText(""+y);
        }
        int z = 0;
        for(int i = 0; i < tableroti.getRowCount();i++){
            z+=Integer.parseInt(tableroti.getValueAt(i, 3).toString());
        }
        txtTotal.setText(z+"");
    }//GEN-LAST:event_btnSubmitActionPerformed
    public PageFormat getPageFormat(PrinterJob pj)
{
    
    PageFormat pf = pj.defaultPage();
    Paper paper = pf.getPaper();    

    double middleHeight =8.0;  
    double headerHeight = 2.0;                  
    double footerHeight = 2.0;                  
    double width = convert_CM_To_PPI(8);      //printer know only point per inch.default value is 72ppi
    double height = convert_CM_To_PPI(headerHeight+middleHeight+footerHeight); 
    paper.setSize(width, height);
    paper.setImageableArea(                    
        0,
        10,
        width,            
        height - convert_CM_To_PPI(1)
    );   //define boarder size    after that print area width is about 180 points
            
    pf.setOrientation(PageFormat.PORTRAIT);           //select orientation portrait or landscape but for this time portrait
    pf.setPaper(paper);    

    return pf;
    }
    protected static double convert_CM_To_PPI(double cm) {            
	        return toPPI(cm * 0.393600787);            
    }
    protected static double toPPI(double inch) {            
	        return inch * 72d;            
    }
    public class BillPrintable implements Printable {
    
   
    
    
  public int print(Graphics graphics, PageFormat pageFormat,int pageIndex) 
  throws PrinterException 
  {    
      
                
        
      int result = NO_SUCH_PAGE;    
        if (pageIndex == 0) {                    
        
            Graphics2D g2d = (Graphics2D) graphics;                    

            double width = pageFormat.getImageableWidth();                    
           
            g2d.translate((int) pageFormat.getImageableX(),(int) pageFormat.getImageableY()); 

            ////////// code by alqama//////////////

            FontMetrics metrics=g2d.getFontMetrics(new Font("Arial",Font.BOLD,7));
        //    int idLength=metrics.stringWidth("000000");
            //int idLength=metrics.stringWidth("00");
            int idLength=metrics.stringWidth("000");
            int amtLength=metrics.stringWidth("000000");
            int qtyLength=metrics.stringWidth("00000");
            int priceLength=metrics.stringWidth("000000");
            int prodLength=(int)width - idLength - amtLength - qtyLength - priceLength-17;

        //    int idPosition=0;
        //    int productPosition=idPosition + idLength + 2;
        //    int pricePosition=productPosition + prodLength +10;
        //    int qtyPosition=pricePosition + priceLength + 2;
        //    int amtPosition=qtyPosition + qtyLength + 2;
            
            int productPosition = 0;
            int discountPosition= prodLength+5;
            int pricePosition = discountPosition +idLength+10;
            int qtyPosition=pricePosition + priceLength + 4;
            int amtPosition=qtyPosition + qtyLength;
            
            
              
        try{
            /*Draw Header*/
            int y=20;
            int yShift = 10;
            int headerRectHeight=15;
            int headerRectHeighta=40;
            
            if(comboxStatus.getSelectedItem().equals("Terjual")){
                
            int z,k;
            String t;
             z =  Integer.parseInt((String) tableroti.getModel().getValueAt(0, 0));
             k = Integer.parseInt((String) tableroti.getModel().getValueAt(1, 0));
             t = ("TKR00"+z+k );
                
            g2d.setFont(new Font("Monospaced",Font.PLAIN,9));
            g2d.drawString("-------------------------------------------",12,y);y+=yShift;
            g2d.drawString("             Toko Roti              ",12,y);y+=yShift;
            g2d.drawString("-------------------------------------------",12,y);y+=headerRectHeight;
            g2d.drawString(" KodeBon : "+t+"      "+LocalTime.now()+"  ",10,y);y+=yShift;
            g2d.drawString("-------------------------------------------",10,y);y+=headerRectHeight;
            for(int i = 0; i < tableroti.getRowCount();i++){
            g2d.drawString(" Kode Roti   : "+((String)tableroti.getModel().getValueAt(i,0))+"  ",10,y);y+=yShift;
            g2d.drawString(" Nama Roti   : "+((String)tableroti.getModel().getValueAt(i,1))+"  ",10,y);y+=yShift;
            g2d.drawString(" Harga       : "+((String)tableroti.getModel().getValueAt(i,3))+"  ",10,y);y+=yShift;
            }
            g2d.drawString("-------------------------------------------",10,y);y+=yShift;
            g2d.drawString(" Total       : Rp. "+txtTotal.getText()+"  ",10,y);y+=yShift;
            g2d.drawString(" Uang        : Rp. "+txtUang.getText()+"    ",10,y);y+=yShift;
            g2d.drawString(" Kembalian   : Rp. "+txtKembalian.getText()+"      ",10,y);y+=yShift;
            g2d.drawString("-------------------------------------------",10,y);y+=yShift;
            g2d.drawString("                Toko Roti                  ",10,y);y+=yShift;
            g2d.drawString("Jl. GGsampingkanan Star Motor No.42-43     ",10,y);y+=yShift;
            g2d.drawString("             Tangerang Selatan             ",10,y);y+=yShift;
            g2d.drawString(" Telp. 021-728 79228, Fax. 021-758 79228   ",10,y);y+=yShift;
            g2d.drawString("*******************************************",10,y);y+=yShift;
            g2d.drawString("         Terima Kasih Sudah Belanja        ",10,y);y+=yShift;
            g2d.drawString("*******************************************",10,y);y+=yShift;
            
            } else {
                int o,e;
             o =  Integer.parseInt((String) tblSellSup.getModel().getValueAt(0, 1));
             e = Integer.parseInt((String) tblSellSup.getModel().getValueAt(1, 1));   
            String t;
             t = (txtkodeSup.getText()+o+e);
             
                g2d.setFont(new Font("Monospaced",Font.PLAIN,9));
            g2d.drawString("-------------------------------------------",12,y);y+=yShift;
            g2d.drawString("             Toko Roti                     ",12,y);y+=yShift;
            g2d.drawString("-------------------------------------------",12,y);y+=headerRectHeight;
            g2d.drawString(" KodeBon : "+t+"       "+LocalTime.now()+" ",10,y);y+=yShift;
            g2d.drawString("-------------------------------------------",10,y);y+=headerRectHeight;
            for(int i = 0; i < tblSellSup.getRowCount();i++){
            g2d.drawString(" Kode Roti   : "+((String)tblSellSup.getModel().getValueAt(i,1))+"  ",10,y);y+=yShift;
            g2d.drawString(" Nama Roti   : "+((String)tblSellSup.getModel().getValueAt(i,3))+"  ",10,y);y+=yShift;
            g2d.drawString(" Harga       : "+((String)tblSellSup.getModel().getValueAt(i,2))+"  ",10,y);y+=yShift;
            }
            g2d.drawString("-------------------------------------------",10,y);y+=yShift;
            g2d.drawString(" Total       : Rp. "+txtTotalsup.getText()+"  ",10,y);y+=yShift;
            g2d.drawString(" Uang        : Rp. "+txtUangsup.getText()+"    ",10,y);y+=yShift;
            g2d.drawString(" Kembalian   : Rp. "+txtKembaliansup.getText()+"      ",10,y);y+=yShift;
            g2d.drawString("-------------------------------------------",10,y);y+=yShift;
            g2d.drawString("                Toko Roti                  ",10,y);y+=yShift;
            g2d.drawString("Jl. GGsampingkanan Star Motor No.42-43     ",10,y);y+=yShift;
            g2d.drawString("             Tangerang Selatan             ",10,y);y+=yShift;
            g2d.drawString(" Telp. 021-728 79228, Fax. 021-758 79228   ",10,y);y+=yShift;
            g2d.drawString("*******************************************",10,y);y+=yShift;
            g2d.drawString("         Terima Kasih Sudah Belanja        ",10,y);y+=yShift;
            g2d.drawString("*******************************************",10,y);y+=yShift;
            
            }      
           
             
           
            
//            g2d.setFont(new Font("Monospaced",Font.BOLD,10));
//            g2d.drawString("Customer Shopping Invoice", 30,y);y+=yShift; 
          

    }
    catch(Exception r){
    r.printStackTrace();
    }

              result = PAGE_EXISTS;    
          }    
          return result;    
      }
   }
    private void cetak_jual(){
         Connection koneksi = null;
        Statement stmt = null;
        try {
            
        koneksi = KoneksiDB.ConnectDb();
        stmt = koneksi.createStatement();
        
        

       for(int i = 0 ; i <  tableroti.getRowCount(); i++){
                    
                stmt.executeUpdate("UPDATE `produksi` SET `status`='"+comboxStatus.getSelectedItem()+"' WHERE `kode_roti`='"+(String)tableroti.getModel().getValueAt(i,0)+"'");
               
        }
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI TAMBAHKAN KE DATABASE!");
        } catch(SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "DATA GAGAL DITAMBAHKAN");
        }
        
    }
    private void btnCetakJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakJualActionPerformed
        // TODO add your handling code here:
     if(txtUang.getText().equals("")){
         JOptionPane.showMessageDialog(rootPane, "SILAHKAN MASUKAN UANG TELEBIH DAHULU!");
     } else {
        PrinterJob pj = PrinterJob.getPrinterJob();        
        pj.setPrintable(new FormAdmin.BillPrintable(),getPageFormat(pj));
        try {
             pj.print();
        }
         catch (PrinterException ex) {
                 ex.printStackTrace();
        }
       cetak_jual();
     }
    }//GEN-LAST:event_btnCetakJualActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        // TODO add your handling code here:
        TxtKodeRoti.setText("");
        txtNamaRoti.setText("");
        txtQuantity.setText("");
        txtHarga.setText("");
        txtTotal.setText("");        
        for (int i = 0; i < tableroti.getRowCount(); i++){
        for(int j = 0; j < tableroti.getColumnCount(); j++) {
            tableroti.setValueAt("", i, j);
      }
    }
    }//GEN-LAST:event_BtnResetActionPerformed
    
    private void auto_number(){
    try{
        String sql = "SELECT MAX(right(kode_supleir,2)) AS no FROM suplier";
        Connection koneksi = KoneksiDB.ConnectDb();
        PreparedStatement proses = koneksi.prepareStatement(sql);
        ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                if(hasil.first() == false){
                    txtkodsup.setText("SP001");
                    
                }else {
                    hasil.last();
                    int auto_id = hasil.getInt(1) + 1;
                    String no = String.valueOf(auto_id);
                    int noLong  = no.length();
                                  for(int a  = 0; a<3-noLong; a++){
                                      no = "0" + no;
                                  }
                                  txtkodsup.setText("SP" + no);
                }
                
            }
    } catch (Exception e) {
        JOptionPane.showInternalMessageDialog(this, "Error: \n" + e.toString(),"ADA KESALAHAN!",JOptionPane.WARNING_MESSAGE);
    }
}
    private void btnBuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuatActionPerformed
        // TODO add your handling code here:
        Connection koneksi = null;
        Statement stmt = null;
        try {
            koneksi = KoneksiDB.ConnectDb();
            stmt = koneksi.createStatement();
            stmt.executeUpdate("INSERT INTO `suplier`(`kode_supleir`, `nama_suplier`, `alamat`, `telepon`, `status`) VALUES ('"+txtkodsup.getText()+"','"+txtnamasup.getText()+"','"+Alamatsup.getText()+"','"+txtTeleponsup.getText()+"','"+comboxsup.getSelectedItem()+"')");
//            System.out.println(fa);
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI TAMBAHKAN KE DATABASE!");
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, "DATA GAGAL DITAMBAHKAN");
        }
        auto_number();
        getData();
    }//GEN-LAST:event_btnBuatActionPerformed

    private void tblSupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblSup.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)tblSup.getModel();
        txtkodsup.setText(model.getValueAt(selectedRow, 0).toString());
        txtnamasup.setText(model.getValueAt(selectedRow, 1).toString());
        Alamatsup.setText(model.getValueAt(selectedRow, 2).toString());
        txtTeleponsup.setText(model.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_tblSupMouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void btnResetSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetSupActionPerformed
        // TODO add your handling code here:
        txtkodsup.setText("");
        txtnamasup.setText("");
        Alamatsup.setText("");
        txtTeleponsup.setText("");
        
    }//GEN-LAST:event_btnResetSupActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        Connection koneksi = null;
        Statement stmt = null;
        try {
            koneksi = KoneksiDB.ConnectDb();
            stmt = koneksi.createStatement();
            stmt.executeUpdate("UPDATE `suplier` SET `nama_suplier`='"+txtnamasup.getText()+"',`alamat`='"+Alamatsup.getText()+"',`telepon`='"+txtTeleponsup.getText()+"',`status`='"+comboxsup.getSelectedItem()+"' WHERE `kode_supleir`='"+txtkodsup.getText()+"'");
//            System.out.println(fa);
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI TAMBAHKAN KE DATABASE!");
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, "DATA GAGAL DITAMBAHKAN");
        }
        auto_number();
        getData();
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtUangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUangKeyReleased
        // TODO add your handling code here:
        int y,z,t;
        y = Integer.parseInt(txtTotal.getText());
        z = Integer.parseInt(txtUang.getText());
        t = (z - y);
        txtKembalian.setText(t+"");
    }//GEN-LAST:event_txtUangKeyReleased

    private void txtUangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUangKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUangKeyPressed

    private void btnCetakJualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCetakJualKeyPressed
        // TODO add your handling code here:
        PrinterJob pj = PrinterJob.getPrinterJob();        
        pj.setPrintable(new FormAdmin.BillPrintable(),getPageFormat(pj));
        try {
             pj.print();
          
        }
         catch (PrinterException ex) {
                 ex.printStackTrace();
        }
        cetak_jual();
    }//GEN-LAST:event_btnCetakJualKeyPressed

    private void txtUangsupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUangsupKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a = Integer.parseInt(txtUangsup.getText());
        b = Integer.parseInt(txtTotalsup.getText());
        c = (a - b);
        txtKembaliansup.setText(""+c);
    }//GEN-LAST:event_txtUangsupKeyReleased

    private void ResetSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetSupActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < tblSellSup.getRowCount(); i++){
            for(int j = 0; j < tblSellSup.getColumnCount(); j++) {
                tblSellSup.setValueAt("", i, j);
            }
        }
        txtkodeSup.setText("");
        txtKodeRoti.setText("");
        txtQuantitysup.setText("");
        TxtHarga1.setText("");
        NamaRotiSup.setText("");
        txtTotalsup.setText("");
    }//GEN-LAST:event_ResetSupActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        searchsuplier();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblSup1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSup1MouseClicked
        // TODO add your handling code here:
        int selectedRow = tblSup1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)tblSup1.getModel();
        txtKodeRoti.setText(model.getValueAt(selectedRow, 0).toString());
        NamaRotiSup.setText(model.getValueAt(selectedRow, 1).toString());
        TxtHarga1.setText(model.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_tblSup1MouseClicked

    private void BtnJualSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJualSupActionPerformed
        // TODO add your handling code here:
        Connection koneksi = null;
        Statement stmt = null;
        if(txtUangsup.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "SILAHKAN MASUKAN UANG TELEBIH DAHULU!");
        } else {
           
            PrinterJob pj = PrinterJob.getPrinterJob();        
            pj.setPrintable(new FormAdmin.BillPrintable(),getPageFormat(pj));
            try {
                 pj.print();
                koneksi = KoneksiDB.ConnectDb();
                stmt = koneksi.createStatement();

                for(int i = 0 ; i <  tblSellSup.getRowCount(); i++){

                    stmt.executeUpdate("UPDATE `produksi` SET `status`='"+comboxsupstatus.getSelectedItem()+"',`suplier_kode`='"+txtkodeSup.getText()+"' WHERE `kode_roti`='"+(String)tblSellSup.getModel().getValueAt(i,1)+"'");

                }
                JOptionPane.showMessageDialog(null, "DATA BERHASIL DI TAMBAHKAN KE DATABASE!");
            } catch(SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "DATA GAGAL DITAMBAHKAN");
            } catch (PrinterException ex) {
                Logger.getLogger(FormAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BtnJualSupActionPerformed

    private void btnSubmitSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitSupActionPerformed
        // TODO add your handling code here:
        if(txtkodeSup.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "SILAHKAN MASUKAN ID SUPPLIER");
        } else {
            DefaultTableModel model = (DefaultTableModel)tblSellSup.getModel();
//            String Status = (String) this.comboxsupstatus.getSelectedItem();
            String KodeSup = this.txtkodeSup.getText();
            String KodeRoti = this.txtKodeRoti.getText();
            String Harga = this.TxtHarga1.getText();
            String Status = this.NamaRotiSup.getText();
            model.addRow(new Object[]{KodeSup,KodeRoti,Harga,Status});

            for(int i = 0; i < tblSellSup.getRowCount();i++){
                int y = tblSellSup.getRowCount();
                txtQuantitysup.setText(""+y);
            }
            int z = 0;
            for(int i = 0; i < tblSellSup.getRowCount();i++){
                z+=Integer.parseInt(tblSellSup.getValueAt(i, 2).toString());
            }
            txtTotalsup.setText(z+"");
        }
    }//GEN-LAST:event_btnSubmitSupActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        searchsiapjualsuplier();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void pencetjual(){
        Connection koneksi = null;
        Statement stmt = null;
        try {

                koneksi = KoneksiDB.ConnectDb();
                stmt = koneksi.createStatement();

                for(int i = 0 ; i <  tblSellSup.getRowCount(); i++){

                    stmt.executeUpdate("UPDATE `produksi` SET `status`='"+comboxsupstatus.getSelectedItem()+"',`suplier_kode`='"+txtkodeSup.getText()+"' WHERE `kode_roti`='"+(String)tblSellSup.getModel().getValueAt(i,1)+"'");

                }
                JOptionPane.showMessageDialog(null, "DATA BERHASIL DI TAMBAHKAN KE DATABASE!");
            } catch(SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "DATA GAGAL DITAMBAHKAN");
            }
    }
    
    private void BtnJualSupKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnJualSupKeyPressed
        // TODO add your handling code here:
        if(txtUangsup.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "SILAHKAN MASUKAN UANG TELEBIH DAHULU!");
        } else {
            PrinterJob pj = PrinterJob.getPrinterJob();        
        pj.setPrintable(new FormAdmin.BillPrintable(),getPageFormat(pj));
        try {
             pj.print();
        }
         catch (PrinterException ex) {
                 ex.printStackTrace();
        }
             pencetjual();
        }
    }//GEN-LAST:event_BtnJualSupKeyPressed

    private void comboxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxStatusActionPerformed

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Alamatsup;
    private javax.swing.JButton BtnJualSup;
    private javax.swing.JButton BtnReset;
    private javax.swing.JMenu Logout;
    private javax.swing.JTextField NamaRotiSup;
    private javax.swing.JButton ResetSup;
    private javax.swing.JTable TableSiapJual;
    private javax.swing.JTextField TxtHarga1;
    private javax.swing.JTextField TxtKodeRoti;
    private javax.swing.JButton TxtSell;
    private javax.swing.JButton btnBuat;
    private javax.swing.JButton btnCetakJual;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnResetSup;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSubmitSup;
    private javax.swing.JComboBox<String> comboxStatus;
    private javax.swing.JComboBox<String> comboxsup;
    private javax.swing.JComboBox<String> comboxsupstatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTable tableroti;
    private javax.swing.JTable tblSellSup;
    private javax.swing.JTable tblSup;
    private javax.swing.JTable tblSup1;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtKembaliansup;
    private javax.swing.JTextField txtKodeRoti;
    private javax.swing.JTextField txtNamaRoti;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtQuantitysup;
    private javax.swing.JTextField txtTeleponsup;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalsup;
    private javax.swing.JTextField txtUang;
    private javax.swing.JTextField txtUangsup;
    private javax.swing.JTextField txtkodeSup;
    private javax.swing.JTextField txtkodsup;
    private javax.swing.JTextField txtnamasup;
    // End of variables declaration//GEN-END:variables
}
